# fly.toml app configuration file generated for pinterest-downloader on 2025-07-09T08:43:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pinterest-downloader'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
